// Copyright (c) 2025 Andrea Enrico Franzoni (andreaenrico.franzoni@gmail.com)
//
// This file is part of fdagwr
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of fdagwr and associated documentation files (the fdagwr software), to deal
// fdagwr without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of fdagwr, and to permit persons to whom fdagwr is
// furnished to do so, subject to the following conditions:
//
// fdagwr IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH fdagwr OR THE USE OR OTHER DEALINGS IN
// fdagwr.


#ifndef FUNCTIONAL_MATRIX_SMOOTHING_HPP
#define FUNCTIONAL_MATRIX_SMOOTHING_HPP

#include "../utility/include_fdagwr.hpp"
#include "../utility/traits_fdagwr.hpp"

#include "functional_matrix.hpp"
#include "../basis/basis_include.hpp"

#include <cassert>


/*!
* @file functional_matrix_smoothing.hpp
* @brief Contains functions to perform the smoothing of a fd represented by a callable object, and a vector containing multiple fd
* @author Andrea Enrico Franzoni
*/



/*!
* @brief Performing the smoothing of fdatum generated by f over a given system of basis
* @tparam INPUT input type of the callable object representing the fdatum
* @tparam OUTPUT output type of the callable object representing the fdatum
* @tparam domain_type the geometry of the basis domain
* @param f a std::function representing the fdatum
* @param basis system of basis (bsplines or constant) over which the smoothing is performed
* @param knots knots over which performing the smoothing
* @return a Eigen::MatrixXd of dimension n_basis x 1, containing the coefficient of the basis expansion
*/
template< typename INPUT = double, typename OUTPUT = double, class domain_type = FDAGWR_TRAITS::basis_geometry >
    requires (std::integral<INPUT> || std::floating_point<INPUT>)  &&  (std::integral<OUTPUT> || std::floating_point<OUTPUT>) && fdagwr_concepts::as_interval<domain_type>
inline
FDAGWR_TRAITS::Dense_Matrix
f_smoothing(const FUNC_OBJ<INPUT,OUTPUT> &f,
            const basis_base_class<domain_type> & basis,
            const FDAGWR_TRAITS::Dense_Matrix & knots)
{
    //evaluating the function all along the knots
    FDAGWR_TRAITS::Dense_Matrix f_ev(knots.rows(),1);
    for(std::size_t i = 0; i < knots.rows(); ++i){    f_ev(i,0) = f(knots(i,0));}

    return basis.smoothing(f_ev,knots);
}

/*!
* @brief Performing the smoothing of multiple fdatum, described by multiple callable objects
* @tparam INPUT input type of the callable object representing the fdatum
* @tparam OUTPUT output type of the callable object representing the fdatum
* @tparam domain_type the geometry of the basis domain
* @param fm a functional_matrix of dimension n x 1, each row is a function containing a callable oject describing a fdatum
* @param basis system of basis (bsplines or constant) over which the smoothing is performed
* @param knots knots over which performing the smoothing
* @return a Eigen::MatrixXd of dimension n_basis x n, containing the coefficient of the basis expansion, where el(i,j) is the coefficient of basis i-th of the basis expansion of the function j-th
*/
template< typename INPUT = double, typename OUTPUT = double, class domain_type = FDAGWR_TRAITS::basis_geometry >
    requires (std::integral<INPUT> || std::floating_point<INPUT>)  &&  (std::integral<OUTPUT> || std::floating_point<OUTPUT>) && fdagwr_concepts::as_interval<domain_type>
inline
FDAGWR_TRAITS::Dense_Matrix
fm_smoothing(const functional_matrix<INPUT,OUTPUT> &fm,
             const basis_base_class<domain_type> & basis,
             const FDAGWR_TRAITS::Dense_Matrix & knots)
{
    assert(fm.cols() == 1);

    std::size_t num_basis = basis.number_of_basis();
    std::size_t num_f = fm.rows();

    //the result is num basis x num functions
    FDAGWR_TRAITS::Dense_Matrix c(num_basis,num_f);

    for (std::size_t i = 0; i < num_f; ++i){ c.col(i) = f_smoothing(fm(i,0),basis,knots).col(0);}
    
    return c;   //num basis x num functions
}

#endif  /*FUNCTIONAL_MATRIX_SMOOTHING_HPP*/