// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// installation_kami_testing
void installation_kami_testing();
RcppExport SEXP _RcppKamiClusterTesting_installation_kami_testing() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    installation_kami_testing();
    return R_NilValue;
END_RCPP
}
// kami_testin
void kami_testin();
RcppExport SEXP _RcppKamiClusterTesting_kami_testin() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    kami_testin();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppKamiClusterTesting_installation_kami_testing", (DL_FUNC) &_RcppKamiClusterTesting_installation_kami_testing, 0},
    {"_RcppKamiClusterTesting_kami_testin", (DL_FUNC) &_RcppKamiClusterTesting_kami_testin, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppKamiClusterTesting(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
