# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

installation_kami_testing <- function() {
    invisible(.Call(`_RcppKamiClusterTesting_installation_kami_testing`))
}

kami_testin <- function() {
    invisible(.Call(`_RcppKamiClusterTesting_kami_testin`))
}

